# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'ubuntu/trusty64'

# Name
VM_NAME = 'personal-AWS-env'

# VM User - 'vagrant' is fine
VM_USER = 'vagrant'

# Username on mac
MAC_USER = 'bryan.praditkul'

# Host folder to sync
HOST_PATH = '/Users/' + MAC_USER + '/' + VM_NAME

# Where to sync to on Guest
GUEST_PATH = '/home/' + VM_USER + '/' + VM_NAME

# VM Port if NAT'ing instead of DHCP
# VM_PORT = 8080 

Vagrant.configure(2) do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX

  # Actual machine name
  config.vm.hostname = VM_NAME

  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
  end

  # DHCP - Comment out if NAT'ing instead
  config.vm.network "private_network", type: "dhcp"

  # Port forwarding - uncomment to use NAT instead of DHCP
  # config.vm.network "forwarded_port", guest: 80, host: VM_PORT

  # Sync folder
  config.vm.synced_folder HOST_PATH, GUEST_PATH

  # Disable default Vagrant folder, use a unique path per project
  config.vm.synced_folder '.', '/home/'+VM_USER+'', disabled: true

  # Installs
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git
    apt-get install -y python-pip
    apt-get install -y python3-pip
  SHELL
end



