#!/bin/bash

exec 2>&1

export JAVA_HOME=/usr/java/jdk1.7.0_40
export ES_HEAP_SIZE=16g
ulimit -l unlimited
ulimit -n 150000

chown -R elasticsearch /srv/var/elasticsearch-logstash

exec setuidgid elasticsearch /opt/elasticsearch/0.90/bin/elasticsearch -f -Des.config=/srv/etc/elasticsearch-logstash/elasticsearch.yml
